seed_everything: 42
data:
  filename: results/prepare_all/coldtarget_posneg_under_class_template_rinerator_label_none_label_none.pkl
  batch_size: 128
  num_workers: 16
model:
  class_path: rindti.models.ClassificationModel
  init_args:
    prot_encoder:
      node_embed:
        class_path: rindti.layers.GINConvNet
      pool:
        class_path: rindti.layers.GMTNet
    drug_encoder:
      node_embed:
        class_path: rindti.layers.GINConvNet
      pool:
        class_path: rindti.layers.GMTNet
    mlp:
      class_path: rindti.layers.MLP
trainer:
  gpus: 1
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 50

optimizer:
  class_path: torch.optim.RMSprop
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CyclicLR
  init_args:
    base_lr: 0.001
    max_lr: 0.01
