seed_everything: 42
data:
  filename: results/distance_based/protein_data_whole_label_none.pkl
  batch_size: 128
  num_workers: 16
model:
  class_path: rindti.models.PfamModel
  init_args:
    node_loss:
      class_path: rindti.losses.NodeLoss
    loss:
      class_path: rindti.losses.PfamCrossEntropyLoss
    masker:
      class_path: rindti.data.DataCorruptor
      init_args:
        x: 0.1
    node_pred:
      class_path: rindti.layers.MLP
    encoder:
      node_embed:
        class_path: rindti.layers.GINConvNet
      pool:
        class_path: rindti.layers.GMTNet
trainer:
  gpus: 1
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 50
optimizer:
  class_path: torch.optim.RMSprop
  init_args:
    lr: 0.001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CyclicLR
  init_args:
    base_lr: 0.001
    max_lr: 0.01
